const express = require('express');
const authController=require('../controllers/auth');
 
const router=express.Router();
router.post('/search_doctor',authController.search_doctor);
router.post('/registerd', authController.registerd);
router.post('/registerp', authController.registerp);
router.post('/logina',authController.logina);
router.post('/loginp',authController.loginp);
router.post('/logind',authController.logind);
router.post('/pay',authController.pay);
router.post('/vprofile',authController.vprofile);
router.post('/v1profile',authController.v1profile);
router.post('/pupdate',authController.pupdate);
router.post('/dupdate',authController.dupdate);
router.post('/pcal',authController.pcal);
router.post('/dcal',authController.dcal);
router.post('/pforgot_pw',authController.pforgot_pw);
router.post('/preset_pw',authController.preset_pw);
router.post('/dforgot_pw',authController.dforgot_pw);
router.post('/dreset_pw',authController.dreset_pw);
router.post('/aforgot_pw',authController.aforgot_pw);
router.post('/areset_pw',authController.areset_pw);
router.post('/admin_confirm',authController.admin_confirm);
router.post('/doctor_auth',authController.doctor_auth);
router.post('/search',authController.search);
module.exports = router;
